### ISSUE TITLE
Error Running roslaunch art_autonomous_exploration everything.launch

### ISSUE THREAD

**Issue by achigeor** [etsardou/intelligent_robot_systems_2016#1]
I get the error below when executing roslaunch art_autonomous_exploration everything.launch: 

```
Map & coverage expansion!
Coverage copy new size: (500, 500)
New coverage info: (500, 500)
[ERROR] [1494008375.553133]: bad callback: <bound method RobotPerception.readMap of <robot_perception.RobotPerception instance at 0x7fb04691d908>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/achilleas/Documents/int_robot_sys/catkin_ws/src/intelligent_robot_systems_2016/art_autonomous_exploration/src/robot_perception.py", line 237, in readMap
    if self.ogm[xx + i, yy + j] > 49 or self.ogm[xx + i, yy + j] == -1:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
The error appears on vanilla code, I haven't yet added anything. I'm on Ubuntu 16.04, with ROS Kinetic.

Before that error I was getting: 
**ImportError: No module named yaml** and then **ImportError: No module named rospkg**. I installed them with pip, and then the error above appeared.

**Comment by etsardou** [comment]
This can be solved by:

```
if self.ogm[int(xx + i), int(yy + j)] > 49 or self.ogm[int(xx + i), int(yy + j)] == -1:
```
